version: '3'
services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'lch_marketplace2'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - backend
    

  truyum-rest-service:

    image: youdev246/truyum-rest

    build: ./

    container_name: truyum-rest-service

    ports:

      - 8080:8080

    depends_on:

      - db

    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lch_marketplace2?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend

       
# Names our volume
volumes:
  my-db:

# Networks to be created to facilitate communication between containers
networks:
  backend: