-- MySQL Script generated by MySQL Workbench
-- Mon Jun 14 11:33:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lch_marketplace
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lch_marketplace` ;

-- -----------------------------------------------------
-- Schema lch_marketplace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lch_marketplace` DEFAULT CHARACTER SET utf8 ;
USE `lch_marketplace` ;

-- -----------------------------------------------------
-- Table `lch_marketplace`.`menu_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lch_marketplace`.`menu_item` ;

CREATE TABLE IF NOT EXISTS `lch_marketplace`.`menu_item` (
  `me_id` INT NOT NULL AUTO_INCREMENT,
  `me_name` VARCHAR(100) NULL,
  `me_price` DECIMAL(8,2) NULL,
  `me_active` VARCHAR(3) NULL,
  `me_date_of_launch` DATE NULL,
  `me_category` VARCHAR(45) NULL,
  `me_free_delivery` VARCHAR(3) NULL,
  PRIMARY KEY (`me_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lch_marketplace`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lch_marketplace`.`user` ;

CREATE TABLE IF NOT EXISTS `lch_marketplace`.`user` (
  `us_id` INT NOT NULL,
  `us_name` VARCHAR(60) NULL,
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lch_marketplace`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lch_marketplace`.`cart` ;

CREATE TABLE IF NOT EXISTS `lch_marketplace`.`cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `ct_us_id` INT NULL,
  `ct_pr_id` INT NULL,
  PRIMARY KEY (`cart_id`),
  CONSTRAINT `fk_cart_menu_item1`
    FOREIGN KEY (`ct_us_id`)
    REFERENCES `lch_marketplace`.`menu_item` (`me_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_user1`
    FOREIGN KEY (`ct_pr_id`)
    REFERENCES `lch_marketplace`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lch_marketplace`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lch_marketplace`.`role` ;

CREATE TABLE IF NOT EXISTS `lch_marketplace`.`role` (
  `ro_id` INT NOT NULL,
  `ro_name` VARCHAR(45) NULL,
  PRIMARY KEY (`ro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lch_marketplace`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lch_marketplace`.`user_role` ;

CREATE TABLE IF NOT EXISTS `lch_marketplace`.`user_role` (
  `ur_role_id` VARCHAR(45) NOT NULL,
  `ur_us_id` INT NULL,
  `ur_ro_id` INT NULL,
  PRIMARY KEY (`ur_role_id`),
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`ur_us_id`)
    REFERENCES `lch_marketplace`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`ur_ro_id`)
    REFERENCES `lch_marketplace`.`role` (`ro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
