-- MySQL Script generated by MySQL Workbench
-- Fri Jun 11 12:41:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema truyum
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema truyum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `truyum` DEFAULT CHARACTER SET utf8;

USE `truyum`;

-- -----------------------------------------------------
-- Table `truyum`.`menu_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_item` (
  `idmenu_item` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10, 2) NOT NULL,
  `active` TINYINT NOT NULL,
  `date_launch` DATE NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `free_delivery` TINYINT NOT NULL,
  PRIMARY KEY (`idmenu_item`)
); 
-- -----------------------------------------------------
-- Table `truyum`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `iduser` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  PRIMARY KEY (`iduser`)
);
 -- -----------------------------------------------------
-- Table `truyum`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cart` (
  `idcart` INT NOT NULL,
  `iduser` INT NOT NULL,
  `idmenu_item` INT NOT NULL,
  PRIMARY KEY (`idcart`, `iduser`, `idmenu_item`),
  CONSTRAINT `fk_cart_user` FOREIGN KEY (`iduser`) REFERENCES `user` (`iduser`),
  CONSTRAINT `fk_cart_menu_item1` FOREIGN KEY (`idmenu_item`) REFERENCES `menu_item` (`idmenu_item`)
);